export const citiesList = [
    'Tokyo',
    'Jakarta',
    'Delhi',
    'Guangzhou',
    'Mumbai',
    'Manila',
    'Shanghai',
    'São Paulo',
    'Seoul',
    'Mexico City',
    'Cairo',
    'New York',
    'Dhaka',
    'Beijing',
    'Kolkāta',
    'Bangkok',
    'Shenzhen',
    'Moscow',
    'Buenos Aires',
    'Lagos',
    'Istanbul',
    'Karachi',
    'Bangalore',
    'Ho Chi Minh City',
    'Ōsaka',
    'Chengdu',
    'Tehran',
    'Kinshasa',
    'Rio de Janeiro',
    'Chennai',
    'Xi’an',
    'Lahore',
    'Chongqing',
    'Los Angeles',
    'Baoding',
    'London',
    'Paris',
    'Linyi',
    'Dongguan',
    'Hyderābād',
    'Tianjin',
    'Lima',
    'Wuhan',
    'Nanyang',
    'Hangzhou',
    'Foshan',
    'Nagoya',
    'Taipei',
    'Tongshan',
    'Luanda',
    'Ganzhou',
    'Kuala Lumpur',
    'Heze',
    'Quanzhou',
    'Chicago',
    'Nanjing',
    'Jining',
    'Hanoi',
    'Pune',
    'Fuyang',
    'Ahmedabad',
    'Johannesburg',
    'Bogotá',
    'Dar es Salaam',
    'Shenyang',
    'Khartoum',
    'Hong Kong',
    'Shaoyang',
    'Zhanjiang',
    'Yancheng',
    'Hengyang',
    'Riyadh',
    'Santiago',
    'Xingtai',
    'Chattogram',
    'Bijie',
    'Shangrao',
    'Zunyi',
    'Sūrat',
    'Surabaya',
    'Nanchong',
    'Xinyang',
    'Madrid',
    'Baghdad',
    'Jieyang',
    'Singapore',
    'Prayagraj',
    'Dalian',
    'Yulin',
    'Changde',
    'Qingdao',
    'Douala',
    'Miami',
    'Xiangyang',
    'Dallas',
    'Houston',
    'Zhengzhou',
    'Lu’an',
    'Jinan',
    'Giza',
    'Zhaotong',
    'Yichun',
    'Nairobi',
    'Guadalajara',
    'Philadelphia',
    'Ankara',
    'Dazhou',
    'Langfang',
    'Yongzhou',
    'Toronto',
    'Saint Petersburg',
    'Qiqihar',
    'Suzhou',
    'Monterrey',
    'Belo Horizonte',
    'Rangoon',
    'Yuncheng',
    'Guilin',
    'Atlanta',
    'Taizhou',
    'Abidjan',
    'Huaihua',
    'Ji’an',
    'Jiujiang',
    'Alexandria',
    'Mianyang',
    'Sydney',
    'Washington',
    'Barcelona',
    'Changsha',
    'Chenzhou',
    'Anqing',
    'Jiangmen',
    'Yibin',
    'Melbourne',
    'Berlin',
    'Kunming',
    'Changchun',
    'Casablanca',
    'Meizhou',
    'Zhangjiakou',
    'Chifeng',
    'Ürümqi',
    'Suzhou',
    'İzmir',
    'Linfen',
    'Kabul',
    'Mogadishu',
    'Luzhou',
    'Hefei',
    'Boston',
    'Liuzhou',
    'Shijiazhuang',
    'Ningbo',
    'Fuzhou',
    'Phoenix',
    'Zhuzhou',
    'Amman',
    'Jeddah',
    'Loudi',
    'Binzhou',
    'Deyang',
    'Taiyuan',
    'Wuhu',
    'Nanning',
    'Harbin',
    'Abuja',
    'Yokohama',
    'Xiamen',
    'Neijiang',
    'Fuzhou',
    'Baicheng',
    'Anshan',
    'Medan',
    'Yulinshi',
    'Wenzhou',
    'Changzhou',
    'Nanchang',
    'Ibadan',
    'Detroit',
    'Montréal',
    'Busan',
    'Hohhot',
    'Seattle',
    'Algiers',
    'Hanzhong',
    'Shiyan',
    'Lucknow',
    'Siping',
    'Mashhad',
    'Changzhi',
    'Dubai',
    'Guiyang',
    'Bengbu',
    'San Francisco',
    'Wuxi',
    'Zhenjiang',
    'Faisalabad',
    'Tongren',
    'Santa Cruz',
    'Qinhuangdao',
    'Tongliao',
    'Jinzhou',
    'San Diego',
    'Jaipur',
    'Xinzhou',
    'Lanzhou',
    'Wuzhou',
    'Athens',
    'Addis Ababa',
    'Chaoyang',
    'Brasília',
    'Taichung',
    'Kuwait City',
    'Budapest',
    'Shaoguan',
    'Rizhao',
    'Kyiv',
    'Sanaa',
    'Incheon',
    'Guatemala City',
    'Birmingham',
    'Zhongshan',
    'Weihai',
    'Daqing',
    'Bursa',
    'Salvador',
    'Rome',
    'Haikou',
    'La Paz',
    'Pyongyang',
    'Minneapolis',
    'Malang',
    'Mudanjiang',
    'Stuttgart',
    'Brooklyn',
    'Kaohsiung',
    'Guayaquil',
    'Lisbon',
    'Longyan',
    'Tieling',
    'Manchester',
    'Baotou',
    'Handan',
    'Cawnpore',
    'Tampa',
    'Zigong',
    'Maracaibo',
    'Mbuji-Mayi',
    'Denver',
    'Weifang',
    'Ankang',
    'Baoshan',
    'Antananarivo',
    'Munich',
    'Santo Domingo',
    'Sanming',
    'Tashkent',
    'Jiamusi',
    'Lincang',
    'Medellín',
    'Shaoxing',
    'Yantai',
    'Huizhou',
    'Hamburg',
    'Guangyuan',
    'Cali',
    'Lusaka',
    'Huangshi',
    'Xining',
    'Ouagadougou',
    'Daegu',
    'Fortaleza',
    'Yaoundé',
    'Jilin',
    'Dandong',
    'Zhuhai',
    'Yingkou',
    'Antalya',
    'Nāgpur',
    'Queens',
    'Accra',
    'Luoyang',
    'Brisbane',
    'Anshun',
    'Shangzhou',
    'Colombo',
    'Baku',
    'Fukuoka',
    'Yan’an',
    'Jincheng',
    'Vancouver',
    'Nantong',
    'Caracas',
    'Konya',
    'Manaus',
    'Eşfahān',
    'Shengli',
    'Taizhou',
    'Harare',
    'Las Vegas',
    'Havana',
    'Perth',
    'Phnom Penh',
    'Puning',
    'Haiphong',
    'Rawalpindi',
    'Yushan',
    'St. Louis',
    'Kumasi',
    'Vadodara',
    'Portland',
    'Vishākhapatnam',
    'Baicheng',
    'Gaziantep',
    'Fushun',
    'Riverside',
    'Bamako',
    'Minsk',
    'Tijuana',
    'Bamenda',
    'Boosaaso',
    'Indore',
    'Şanlıurfa',
    'Vienna',
    'Karaj',
    'Kananga',
    'Peshawar',
    'Sapporo',
    'Pingxiang',
    'Orlando',
    'Aleppo',
    'Sacramento',
    'Almaty',
    'San Juan',
    'San Antonio',
    'Yinchuan',
    'Santos',
    'Blantyre',
    'Bucharest',
    'Curitiba',
    'Multan',
    'Tainan',
    'Port Harcourt',
    'Warsaw',
    'Jixi',
    'Saidu Sharif',
    'Liaoyang',
    'Beihai',
    'Brazzaville',
    'Fuxin',
    'Mersin',
    'Bhopāl',
    'Lubumbashi',
    'Denpasar',
    'Davao',
    'Adana',
    'Damascus',
    'Brussels',
    'Hyderabad City',
    'Diyarbakır',
    'San Jose',
    'Montevideo',
    'Pittsburgh',
    'Cincinnati',
    'Benxi',
    'Baiyin',
    'Mosul',
    'Kampala',
    'Patna',
    'Tegucigalpa',
    'Cleveland',
    'Heihe',
    'Jingdezhen',
    'Conakry',
    'Recife',
    'Indianapolis',
    'Austin',
    'Kansas City',
    'Novosibirsk',
    'Bilāspur',
    'Semarang',
    'Ludhiāna',
    'Stockholm',
    'Āgra',
    'León de los Aldama',
    'Puebla',
    'Madurai',
    'Córdoba',
    'Shīrāz',
    'Jamshedpur',
    'Tabrīz',
    'Huzhou',
    'Columbus',
    'Sofia',
    'Palembang',
    'Zhangjiajie',
    'Jiaxing',
    'Charlotte',
    'Panama City',
    'Belém',
    'Virginia Beach',
    'Gwangju',
    'Porto Alegre',
    'Valencia',
    'Onitsha',
    'Abu Dhabi',
    'Daejeon',
    'Yekaterinburg',
    'Kyōto',
    'Dakar',
    'Kharkiv',
    'Guyuan',
    'Khulna',
    'Muscat',
    'Farīdābād',
    'Chizhou',
    'Tel Aviv-Yafo',
    'Ulaanbaatar',
    'Goiânia',
    'Kayseri',
    'Belgrade',
    'Milan',
    'Aurangābād',
    'Copenhagen',
    'Huangshan',
    'Auckland',
    'Makassar',
    'Santiago',
    'Milwaukee',
    'Rājkot',
    'Prague',
    'Samsun',
    'Barranquilla',
    'Guarulhos',
    'Al Başrah',
    'Mandalay',
    'Juárez',
    'Adelaide',
    'Baishan',
    'Tripoli',
    'Huaiyin',
    'Rosario',
    'Helsinki',
    'Jabalpur',
    'Providence',
    'Nizhniy Novgorod',
    'Ahvāz',
    'Shaoyang',
    'Sharjah',
    'Kazan',
    'Suwon',
    'Calgary',
    'Cần Thơ',
    'Yiwu',
    'Jacksonville',
    'Mombasa',
    'Chelyabinsk',
    'Vārānasi',
    'Xinyu',
    'Qom',
    'Hargeysa',
    'Zhangye',
    'Hiroshima',
    'Maiduguri',
    'Chiang Mai',
    'Doha',
    'Maputo',
    'Mbandaka',
    'Medina',
    'Srīnagar',
    'Omsk',
    'Dublin',
    'Cilacap',
    'Bandar Lampung',
    'Ulsan',
    'Dhanbād',
    'Nay Pyi Taw',
    'Kigali',
    'Bukavu',
    'Bafoussam',
    'Yichun',
    'Benin City',
    'Rostov',
    'Xiantao',
    'Amritsar',
    'Salt Lake City',
    'Tbilisi',
    'Ufa',
    'Fès',
    'São Luís',
    'Sevilla',
    'N’Djamena',
    'Mexicali',
    'Nashville',
    'Tamale',
    'Yuyao',
    'Krasnoyarsk',
    'Cologne',
    'Bujumbura',
    'Bishkek',
    'São Gonçalo',
    'Yerevan',
    'Ezhou',
    'Nur-Sultan',
    'Nouakchott',
    'Rānchi',
    'Gwalior',
    'Zhongwei',
    'Goyang',
    'Oslo',
    'Chandīgarh',
    'Edmonton',
    'Sendai',
    'Raleigh',
    'Tunis',
    'Barquisimeto',
    'Voronezh',
    'Perm',
    'Bogor',
    'Cartagena',
    'Jodhpur',
    'Memphis',
    'Managua',
    'Sanya',
    'Shymkent',
    'Niamey',
    'Denizli',
    'Maceió',
    'Monrovia',
    'Louisville',
    'Odesa',
    'Volgograd',
    'Port-au-Prince',
    'Raipur',
    'Arequipa',
    'Richmond',
    'Buffalo',
    'Xingyi',
    'Quetta',
    'Kathmandu',
    'Ottawa',
    'Lilongwe',
    'Asmara',
    'Freetown',
    'Vientiane',
    'Jerusalem',
    'Riga',
    'Bangui',
    'Dushanbe',
    'Lomé',
    'Ashgabat',
    'Zagreb',
    'Libreville',
    'Cotonou',
    'Pretoria',
    'Vilnius',
    'Winnipeg',
    'Quebec City',
    'Chisinau',
    'Port Moresby',
    'Skopje',
    'Djibouti',
    'Gaza',
    'Kingston',
    'Rabat',
    'San Salvador',
    'The Hague',
    'Asunción',
    'Juba',
    'Maseru',
    'Bissau',
    'Bratislava',
    'Kitchener',
    'Manama',
    'Tallinn',
    'Beirut',
    'Cape Town',
    'Tirana',
    'Sarajevo',
    'Wellington',
    'Banjul',
    'Halifax',
    'Canberra',
    'Yamoussoukro',
    'Nicosia',
    'Windhoek',
    'Saint-Denis',
    'Sucre',
    'Ljubljana',
    'Nassau',
    'Bloemfontein',
    'Fort-de-France',
    'Gaborone',
    'Paramaribo',
    'Dodoma',
    'Georgetown',
    'Gibraltar',
    'Malabo',
    'Suva',
    'Nouméa',
    'Pristina',
    'Male',
    'Port Louis',
    'Podgorica',
    'Willemstad',
    'Bern',
    'Gitega',
    'Reykjavík',
    'Luxembourg',
    'Papeete',
    'Praia',
    'Sri Jayewardenepura Kotte',
    'Moroni',
    'Mbabane',
    'Honiara',
    'Port of Spain',
    'Castries',
    'Cayenne',
    'São Tomé',
    'Port-Vila',
    'Bandar Seri Begawan',
    'Apia',
    'Tarawa',
    'Oranjestad',
    'Mamoudzou',
    'Majuro',
    'Douglas',
    'George Town',
    'Kingstown',
    'Saint John’s',
    'Nuku‘alofa',
    'Nuuk',
    'Belmopan',
    'Roseau',
    'Basseterre',
    'Pago Pago',
    'Grand Turk',
    'Marigot',
    'Funafuti',
    'Philipsburg',
    'Stanley',
    'Hamilton',
    'Basse-Terre',
    'Jamestown',
    'Saint-Pierre',
    'The Valley',
    'Kingston',
    'Longyearbyen',
    'Bareilly',
    'Oklahoma City',
    'Xingcheng',
    'Chiba',
    'Pekanbaru',
    'Dnipro',
    'Natal',
    'Nada',
    'Zamboanga City',
    'Kirkuk',
    'Bridgeport',
    'Naples',
    'Morelia',
    'Málaga',
    'Cebu City',
    'Coimbatore',
    'Taishan',
    'Teresina',
    'Solāpur',
    'Tangier',
    'Kermānshāh',
    'Krasnodar',
    'Baidoa',
    'Gaalkacyo',
    'El Alto',
    'Kitakyūshū',
    'Aguascalientes',
    'Marrakech',
    'Donetsk',
    'New Orleans',
    'Trichinopoly',
    'Kashgar',
    'Santiago de Cuba',
    'Owerri',
    'Padang',
    'Santiago del Estero',
    'Daye',
    'Fort Worth',
    'Hartford',
    'Campo Grande',
    'Bobo-Dioulasso',
    'Ad Dammām',
    'Quzhou',
    'Lhasa',
    'Bunia',
    'Cancún',
    'Mérida',
    'Dengtalu',
    'Abeokuta',
    'Zhoushan',
    'Natal',
];
