import './globals.css'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registery'
import Navbar from '../components/Nav/Navbar'
import { ReduxProvider } from '@/redux/ReduxProvider'
import Theme from '../Theme/Theme'
import { GlobalStyles } from '@/Theme/ThemeColors'

import { AppDispatch,useAppSelector } from "@/redux/store";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <ReduxProvider>

            <StyledComponentsRegistry>
              <Theme>
                <GlobalStyles />
                <Navbar />
                {children}
              </Theme>

            </StyledComponentsRegistry>

        </ReduxProvider>

      </body>
    </html>
  )
}
