"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GrandChildDivBottom = exports.GrandChildDivTop = exports.GrandChildDiv = exports.ChildDivTop = exports.ChildDivBottom = exports.ChildDiv = exports.MainDiv = void 0;
var styled_components_1 = require("styled-components");
var framer_motion_1 = require("framer-motion");
exports.MainDiv = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    height:800px;\n    width:80%;\n    display:flex;\n    margin:200px auto;\n    flex-direction: column;\n\n    @media (max-width:750px){\n        margin:200px auto 50px ;\n    }\n\n"], ["\n    height:800px;\n    width:80%;\n    display:flex;\n    margin:200px auto;\n    flex-direction: column;\n\n    @media (max-width:750px){\n        margin:200px auto 50px ;\n    }\n\n"])));
exports.ChildDiv = styled_components_1.default.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    height:600px;\n    width:100%;\n    display:flex;\n    justify-content: space-between;\n\n    /* @media (max-width:750px){\n        flex-direction: column;\n        align-items: center;\n        justify-content:center\n    } */\n"], ["\n    height:600px;\n    width:100%;\n    display:flex;\n    justify-content: space-between;\n\n    /* @media (max-width:750px){\n        flex-direction: column;\n        align-items: center;\n        justify-content:center\n    } */\n"])));
exports.ChildDivBottom = (0, styled_components_1.default)(exports.ChildDiv)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n\n    @media (max-width:1200px){\n        flex-direction:column;\n        align-items:center;\n        justify-content:center;\n        margin-top:40px\n    }\n"], ["\n\n    @media (max-width:1200px){\n        flex-direction:column;\n        align-items:center;\n        justify-content:center;\n        margin-top:40px\n    }\n"])));
exports.ChildDivTop = (0, styled_components_1.default)(exports.ChildDiv)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    @media (max-width:750px){\n        flex-direction:column;\n        align-items:center;\n        justify-content:center;\n    }\n"], ["\n    @media (max-width:750px){\n        flex-direction:column;\n        align-items:center;\n        justify-content:center;\n    }\n"])));
exports.GrandChildDiv = (0, styled_components_1.default)(framer_motion_1.motion.div)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n\n    height:inherit;\n    width:", ";\n    display:flex;\n    flex-direction:column;\n\n    justify-content: ", " ;\n    align-items: ", ";\n\n    /* @media (max-width:1400px){\n        width:", ";\n    }\n\n    @media (max-width:1000px){\n        width:50%\n    }\n    @media (max-width:850px){\n        width:40%;\n    } */\n\n    /* @media (max-width:750px){\n        justify-content: center;\n        width:80%;\n        height:80%;\n        order: ", ";\n    } */\n"], ["\n\n    height:inherit;\n    width:", ";\n    display:flex;\n    flex-direction:column;\n\n    justify-content: ", " ;\n    align-items: ", ";\n\n    /* @media (max-width:1400px){\n        width:", ";\n    }\n\n    @media (max-width:1000px){\n        width:50%\n    }\n    @media (max-width:850px){\n        width:40%;\n    } */\n\n    /* @media (max-width:750px){\n        justify-content: center;\n        width:80%;\n        height:80%;\n        order: ", ";\n    } */\n"])), function (props) { return props.width; }, function (props) { return props.justify; }, function (props) { return props.align; }, function (props) { return props.widthRes; }, function (props) { return props.order; });
exports.GrandChildDivTop = (0, styled_components_1.default)(exports.GrandChildDiv)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n\n    @media (max-width:1400px){\n        width:", ";\n    }\n\n    @media (max-width:1000px){\n        width:50%\n    }\n    @media (max-width:850px){\n        width:40%;\n    }\n\n    @media (max-width:750px){\n        width:68%;\n        justify-content:end;\n        align-items: ", ";\n        order: ", ";\n        text-align:center;\n\n\n    }\n"], ["\n\n    @media (max-width:1400px){\n        width:", ";\n    }\n\n    @media (max-width:1000px){\n        width:50%\n    }\n    @media (max-width:850px){\n        width:40%;\n    }\n\n    @media (max-width:750px){\n        width:68%;\n        justify-content:end;\n        align-items: ", ";\n        order: ", ";\n        text-align:center;\n\n\n    }\n"])), function (props) { return props.widthRes; }, function (props) { return props.text ? 'center' : 'center'; }, function (props) { return props.order; });
exports.GrandChildDivBottom = (0, styled_components_1.default)(exports.GrandChildDiv)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n        @media (max-width:1400px){\n        width:", ";\n        height:200px;\n    }\n\n    @media (max-width:1200px){\n        width:90%;\n        align-items:center\n    }\n\n\n    @media (max-width:750px){\n        margin:50px;\n        width:inherit;\n        justify-content:center;\n        align-items: ", ";\n        order: ", ";\n        text-align:center;\n\n\n\n    }\n"], ["\n        @media (max-width:1400px){\n        width:", ";\n        height:200px;\n    }\n\n    @media (max-width:1200px){\n        width:90%;\n        align-items:center\n    }\n\n\n    @media (max-width:750px){\n        margin:50px;\n        width:inherit;\n        justify-content:center;\n        align-items: ", ";\n        order: ", ";\n        text-align:center;\n\n\n\n    }\n"])), function (props) { return props.widthRes; }, function (props) { return props.text ? 'center' : 'center'; }, function (props) { return props.order; });
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7;
